kind: Deployment
apiVersion: apps/v1
metadata:
  name: camel-quarkus-examples-rest-json
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camel-quarkus-examples-rest-json
  template:
    metadata:
      labels:
        app: camel-quarkus-examples-rest-json
    spec:
      containers:
        - name: camel-quarkus-examples-rest-json
          image: camel-quarkus-examples-rest-json:latest
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name: camel-quarkus-examples-rest-json-svc
spec:
ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
selector:
  app: camel-quarkus-examples-rest-json